name: Ascii

on: push

jobs:
  build-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Install cowsay
        run: |
          sudo apt-get update
          sudo apt-get install -y cowsay

      - name: Display Ascii Art
        run: |
          cowsay -f dragon "Welcome to the Ascii Art Workflow!" >> ascii_art.txt
      - name: upload ascii art File
        uses: actions/upload-artifact@v4
        with:
          name: ascii-art
          path : ascii_art.txt

      - name: Sleep for 30 seconds
        run: sleep 30

  test-job-2:
    needs: build-job-1
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 10 seconds
      run: sleep 10

    - name: Download ascii art file
      uses: actions/download-artifact@v5
      with:
        name: ascii-art
        path: ascii_art.txt

   


  deploy-job-3:
    needs: test-job-2
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10
      - name: Download ascii art file
        uses: actions/download-artifact@v5
        with:
          name: ascii-art
          path: ascii_art.txt

      - name: Display Ascii Art File
        run: |
          cat ascii_art.txt
      - name: Deploy Step
        run: echo "Deploying Ascii Art Application..."
      - name: Final Message
        run: echo "Ascii Art Workflow Completed!"

        