name : My First Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - run: cat README.md

      - name: Say Hello
        run: echo "Hello, World!"
      - name: Show Current Directory
        run: pwd
      - name: List Files
        run: ls -la
      - name: Show Date and Time
        run: date
      - name: Install cowsay
        run: | 
          chmod +x ascii.sh
          ./ascii.sh