name : My First Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - run: cat README.md

      - name: Say Hello
        run: echo "Hello, World!"
      - name: Show Current Directory
        run: pwd
      - name: List Files
        run: ls -la
      - name: Show Date and Time
        run: date
      - name: Install cowsay
        run: sudo apt-get install -y cowsay
      - name: Generate ascii art
        run: cowsay -f dragon "This is my first GitHub Action!" >> ascii_art.txt
      - name: Display ascii art
        run: cat ascii_art.txt
