name : My First Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Say Hello
        run: echo "Hello, World!"
      - name: Show Current Directory
        run: pwd
      - name: List Files
        run: ls -la
        